//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public long tagId { get; set; }
        public string tagName { get; set; }
        public long userId { get; set; }
        public Nullable<long> photoId { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
