//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CategoryType.
        /// </summary>
        internal static string categoryType {
            get {
                return ResourceManager.GetString("categoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comment Date.
        /// </summary>
        internal static string commentDate {
            get {
                return ResourceManager.GetString("commentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comment Description.
        /// </summary>
        internal static string commentDescription {
            get {
                return ResourceManager.GetString("commentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diaphragm.
        /// </summary>
        internal static string dia {
            get {
                return ResourceManager.GetString("dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exhibition time.
        /// </summary>
        internal static string exhi {
            get {
                return ResourceManager.GetString("exhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iso.
        /// </summary>
        internal static string iso {
            get {
                return ResourceManager.GetString("iso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Likes.
        /// </summary>
        internal static string like {
            get {
                return ResourceManager.GetString("like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LoginName.
        /// </summary>
        internal static string loginName {
            get {
                return ResourceManager.GetString("loginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandatory Field.
        /// </summary>
        internal static string mandatoryField {
            get {
                return ResourceManager.GetString("mandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Photo.
        /// </summary>
        internal static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PhotoDate.
        /// </summary>
        internal static string photoDate {
            get {
                return ResourceManager.GetString("photoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PhotoId.
        /// </summary>
        internal static string photoId {
            get {
                return ResourceManager.GetString("photoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a White balance.
        /// </summary>
        internal static string wb {
            get {
                return ResourceManager.GetString("wb", resourceCulture);
            }
        }
    }
}
